spring:
  application:
    name: quizcard
  kafka:
    bootstrap-servers: pkc-n98pk.us-west-2.aws.confluent.cloud:9092
    consumer:
      topic: user_assessment_result
      group-id: quiz-result-group
      auto-offset-reset: earliest
    producer:
      topic: user_assessment_feature
  confluent:
    schema-registry:
      registry-url: "https://psrc-1ryeo07.us-west-2.aws.confluent.cloud"
  datasource:
    url: jdbc:postgresql://localhost:5433/quizcard_flink_db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2