version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: quizcard-flink-postgres
    environment:
      POSTGRES_DB: quizcard_flink_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - quizcard_flink_postgres_data:/var/lib/postgresql/data   # persist data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # auto-run on first start
    restart: unless-stopped

volumes:
  quizcard_flink_postgres_data: